# Configuration file for the Multi-Modal Content Moderation System

# Model Configuration
model:
  text_model: "bert-base-uncased"
  image_model: "google/vit-base-patch16-224"
  fusion_strategy: "attention"  # Options: concat, attention, cross_attention
  num_classes: 5
  dropout_rate: 0.3
  freeze_backbone: false

# Training Configuration
training:
  batch_size: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  num_epochs: 10
  warmup_steps: 100
  max_grad_norm: 1.0
  validation_split: 0.2
  test_split: 0.1
  save_dir: "checkpoints"
  log_interval: 100

# Data Configuration
data:
  max_text_length: 512
  image_size: 224
  train_data_path: "data/processed/train.csv"
  val_data_path: "data/processed/val.csv"
  test_data_path: "data/processed/test.csv"
  text_column: "text"
  image_column: "image_path"
  label_column: "label"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  max_content_length: 10485760  # 10MB
  timeout: 30
  enable_cors: true
  docs_url: "/docs"
  redoc_url: "/redoc"

# Frontend Configuration
frontend:
  api_base_url: "http://localhost:8000"
  page_title: "Content Moderation System"
  page_icon: "🛡️"
  default_threshold: 0.5

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_file: "logs/app.log"

# Monitoring Configuration
monitoring:
  enable_wandb: false
  wandb_project: "content-moderation"
  wandb_entity: "your-team"
  metrics_interval: 100

# Class Labels
classes:
  - "Safe"
  - "Hate Speech"
  - "Violence"
  - "Sexual Content"
  - "Harassment"

# Data Collection
data_collection:
  datasets:
    - "hate_speech18"
    - "hatexplain"
    - "ucberkeley-dlab/measuring-hate-speech"
  reddit:
    subreddits:
      - "politics"
      - "news"
      - "worldnews"
    limit: 1000
  images:
    safe_images_count: 5000
    hateful_memes: true

# Evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1"
  cross_validation_folds: 5
  bias_analysis: true
  interpretability: true
